### ISSUE TITLE
Using Virtualbox for encapsulation

### ISSUE THREAD

**Issue by phros** [jtesta/ssh-mitm#6]
Hi jtesta,

first of all, thanks for the awesome work of yours!

I'm trying to use your ssh-mitm in my man in the middle setup. I have a notebook opening a wifi-hotspot, redirecting every traffic to the www. So I have control over all the traffic.

Now, I have installed your script inside a VirtualBox VM. Now I use several script for forwarding all the:

```
User connects to 22
MITM proxy intercepts incoming connections on port 22 ->  localhost port 2222
Virtualbox listens on port 2222 and redirects to port 22 inside the VM (where sshmitm is listening)
```
When connecting with a device to my targeted ssh-server, the credentials get intercepted, this happens a lot of time. It seems like the ssh session is spawned a lots of times, on a lot of different ports. But no real ssh session is spawned. I get a lot of session logs which are all empty. 

Is there anything I am missing? Can you give me any hint where to search for the problem? If you need more information about the setup, I give my best to provide it.

Cheers!

**Comment by jtesta** [comment]
Glad to hear you're getting lots of creds!

I suspect that you're not logging any sessions because you're intercepting SFTP connections.  Currently, ssh-mitm doesn't have that implemented (its on the to-do list).  Instead, SFTP connections just get terminated immediately after authentication.  Beware that this interferes with what users are doing on the network!  They'll get upset since they can't do their work, and start investigating...

If you have access to another machine on the network, you can double check this is the case by starting an SSH session as well as an SFTP session.  The SSH session should get logged, whereas the SFTP session will result in an empty log file.

**Comment by phros** [comment]
Thanks for your reply! I am not using SFTP. I set up an SSH server (openssh) which can be reached from within my sshmitm VM and through my whole mitm setup, if I don't intercept the connection. I expected a problem within the couple of redirecting but don't know how to debug it....

**Comment by phros** [comment]
Hi, currently I have the state, that I can connect to my sshmitm, but the sshmitm does not connect to the actual target. I started the sshmitm program with the debug flag and appended the log.
[out.txt](https://github.com/jtesta/ssh-mitm/files/1084379/out.txt)

**Comment by jtesta** [comment]
My apologies for the slow response.  I've been putting my time into v1.1, which was just released.  It will now log more about what its doing, which could help debug this.  Please give it a whirl and see if /var/log/auth.log gives any better hints.

Another possibility is that the machine you're running ssh-mitm on can't resolve the hosts that the victims are trying to connect to.

**Comment by phros** [comment]
Thanks for reply, I will check it (can take some time).

**Comment by phros** [comment]
Thanks, with the latest update, my virtual box encapsulation solution is no longer needed! Everything works like now.
